"use client";

import { useEffect, useMemo, useState } from "react";
import scheduleSource from "../src/data/schedule-v2.json";
import substitutionSource from "../src/data/substitutions-v2.json";

type Tab = "groups" | "days" | "subjects" | "teachers" | "loads" | "substitutions";
type TeacherType = "all" | "tutors" | "specialists" | "shared" | "support";
type SubjectType = "all" | "tutoring" | "core" | "lang" | "spec";
type SubstitutionView = "resolver" | "availability";
type Lesson = { group: string; day: string; time: string; minutes: number; subject: string; primary: string; shared: string[]; notes: string };
type Load = { direct: number; shared: number; recess: number; family: number; coordination: number; tutorial: number; computed: number; support: number; total: number };
type TeacherState = { status: string; kind: string };
type SlotState = { day: string; slot: string; teachers: Record<string, TeacherState> };
type Scenario = Record<string, string>;

const schedule = scheduleSource as typeof scheduleSource & { lessons: Lesson[]; teacherLoads: Record<string, Load>; teacherRoles: Record<string, string[]> };
const substitutions = substitutionSource as typeof substitutionSource & { slots: SlotState[]; scenarios: Scenario[] };
const DAYS = schedule.days;
const GROUPS = schedule.groups;
const TEACHERS = schedule.teachers;
const CORE = ["Lengua", "Matemáticas", "C. Naturales", "C. Sociales"];
const LANGUAGES = ["Inglés", "Francés"];
const PRIORITIES = [
  ["P1 Misma docencia compartida", "P1 · Misma docencia compartida"],
  ["P2 Apoyo", "P2 · Apoyo"],
  ["P3 DC otro grupo", "P3 · Docencia compartida en otro grupo"],
  ["P4 Atención familias", "P4 · Atención a familias"],
  ["P5 Coordinación/tutoría", "P5 · Coordinación / reducción tutorial"],
] as const;

function family(subject: string) { return CORE.includes(subject) ? "core" : LANGUAGES.includes(subject) ? "lang" : "spec"; }
function normalized(value: string) { return value.toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); }
function matches(query: string, ...values: string[]) { return !query || normalized(values.join(" ")).includes(normalized(query)); }
function formatMinutes(minutes: number) { if (!minutes) return "—"; const hours = Math.floor(minutes / 60); const remainder = minutes % 60; return `${hours ? `${hours} h` : ""}${hours && remainder ? " " : ""}${remainder ? `${remainder} min` : ""}`; }
function lessonsFor(group: string, day: string) { return schedule.lessons.filter((lesson) => lesson.group === group && lesson.day === day); }
function isRecess(day: string, time: string) { return schedule.recess[day as keyof typeof schedule.recess] === time; }

export default function Home() {
  const [tab, setTab] = useState<Tab>("groups");
  const [group, setGroup] = useState("4.º");
  const [day, setDay] = useState("Lunes");
  const [teacher, setTeacher] = useState("María Molina");
  const [teacherType, setTeacherType] = useState<TeacherType>("all");
  const [subjectType, setSubjectType] = useState<SubjectType>("all");
  const [subject, setSubject] = useState("all");
  const [query, setQuery] = useState("");
  const exportCsv = () => {
    const rows = [["Grupo", "Día", "Hora", "Asignatura", "Docente principal", "Docencia compartida"], ...schedule.lessons.filter((lesson) => lesson.group === group).map((lesson) => [lesson.group, lesson.day, lesson.time, lesson.subject, lesson.primary, lesson.shared.join(" + ")])];
    const csv = rows.map((row) => row.map((value) => `"${value.replaceAll('"', '""')}"`).join(",")).join("\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
    const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = `horario-${group}.csv`; anchor.click(); URL.revokeObjectURL(anchor.href);
  };
  const nav = <>{navButton("groups", "Grupos", "▦", tab, setTab)}{navButton("days", "Por días", "◫", tab, setTab)}{navButton("subjects", "Asignaturas", "▤", tab, setTab)}{navButton("teachers", "Docentes", "♙", tab, setTab)}{navButton("loads", "Cargas", "▥", tab, setTab)}{navButton("substitutions", "Sustituciones", "⇄", tab, setTab)}</>;
  return <main className="app theme-compact">
    <aside className="sidebar" aria-label="Navegación principal"><div className="mark"><img src="./logo-srl-v4.webp" alt="Colegio Público Santa Rosa de Lima"/><div><b>Horarios</b><small>Sta. Rosa de Lima</small><em>Curso 26–27</em></div></div><nav>{nav}</nav></aside>
    <section className="shell"><header className="topbar"><div className="topbar-brand"><img className="mobile-school-logo" src="./logo-srl-v4.webp" alt="Colegio Público Santa Rosa de Lima"/><div><h1>Horarios CEIP <span>· Curso 2026–27</span></h1></div></div></header><div className="mobile-nav">{nav}</div>
      {tab === "groups" && <><Toolbar query={query} setQuery={setQuery}><label>Grupo<select value={group} onChange={(event) => setGroup(event.target.value)}>{GROUPS.map((name) => <option key={name}>{name}</option>)}</select></label><button className="secondary" onClick={exportCsv}>↓ Exportar CSV</button><button className="primary" onClick={() => window.print()}>Imprimir horario</button></Toolbar><section className="panel schedule-panel"><PanelTitle eyebrow="Vista semanal" title={`${group} Primaria`}/><WeekGrid group={group} query={query}/></section></>}
      {tab === "days" && <DayView day={day} setDay={setDay} query={query} setQuery={setQuery}/>}
      {tab === "subjects" && <SubjectsView subjectType={subjectType} setSubjectType={setSubjectType} subject={subject} setSubject={setSubject} query={query} setQuery={setQuery}/>}
      {tab === "teachers" && <TeacherView teacher={teacher} setTeacher={setTeacher} teacherType={teacherType} setTeacherType={setTeacherType} query={query} setQuery={setQuery}/>}
      {tab === "loads" && <LoadsView/>}{tab === "substitutions" && <SubstitutionsView/>}
    </section>
  </main>;
}

function navButton(id: Tab, label: string, icon: string, tab: Tab, setTab: (tab: Tab) => void) { return <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><span>{icon}</span>{label}</button>; }
function Toolbar({ children, query, setQuery, placeholder = "Buscar asignatura o docente…" }: { children: React.ReactNode; query: string; setQuery: (value: string) => void; placeholder?: string }) { return <div className="toolbar">{children}<label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder}/></label></div>; }
function Legend() { return <div className="legend"><span className="legend-item core"><i/>Troncales</span><span className="legend-item lang"><i/>Idiomas</span><span className="legend-item spec"><i/>Especialidades</span></div>; }
function PanelTitle({ eyebrow, title, aside = <Legend/> }: { eyebrow: string; title: string; aside?: React.ReactNode }) { return <div className="panel-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{aside}</div>; }

function LessonCard({ lesson, query, compact = false }: { lesson: Lesson; query: string; compact?: boolean }) {
  const visible = matches(query, lesson.subject, lesson.primary, ...lesson.shared);
  return <article className={`${compact ? "matrix-card" : "lesson"} family-${family(lesson.subject)} ${visible ? "" : "muted"}`}><span className="lesson-time">{lesson.time}</span><strong>{lesson.subject}</strong><small><b>Docente:</b> {lesson.primary}</small>{lesson.shared.length > 0 && <small><b>Docencia compartida:</b> {lesson.shared.join(", ")}</small>}</article>;
}

function WeekGrid({ group, query }: { group: string; query: string }) {
  return <div className="week-grid">{DAYS.map((day) => <div className="day" key={day}><h3>{day}</h3><div className="day-cards">{schedule.slots[day as keyof typeof schedule.slots].map((time) => { if (isRecess(day, time)) return <div className="break" key={time}><span>☕</span> Recreo · 30 min</div>; const lesson = lessonsFor(group, day).find((item) => item.time === time); return lesson ? <LessonCard key={time} lesson={lesson} query={query}/> : null; })}</div></div>)}</div>;
}

function DayView({ day, setDay, query, setQuery }: { day: string; setDay: (day: string) => void; query: string; setQuery: (value: string) => void }) {
  const slots = schedule.slots[day as keyof typeof schedule.slots];
  return <><Toolbar query={query} setQuery={setQuery}><label>Día<select value={day} onChange={(event) => setDay(event.target.value)}>{DAYS.map((name) => <option key={name}>{name}</option>)}</select></label></Toolbar><section className="panel day-overview"><PanelTitle eyebrow="Organización diaria" title={day} aside={<><span className="validation">9 grupos · franjas oficiales</span><Legend/></>}/><div className="matrix-wrap"><div className="day-matrix" style={{ gridTemplateColumns: `120px repeat(${slots.length}, minmax(205px, 1fr))` }}><div className="matrix-heading">Grupo</div>{slots.map((time) => <div className="matrix-heading" key={time}>{time}</div>)}{GROUPS.map((group) => <div className="matrix-row" key={group}><div className="matrix-group">{group}</div>{slots.map((time) => { if (isRecess(day, time)) return <div className="matrix-recess" key={time}>☕ Recreo</div>; const lesson = lessonsFor(group, day).find((item) => item.time === time); return <div className="matrix-cell" key={time}>{lesson ? <LessonCard lesson={lesson} query={query} compact/> : <span>—</span>}</div>; })}</div>)}</div></div></section></>;
}

function SubjectsView({ subjectType, setSubjectType, subject, setSubject, query, setQuery }: { subjectType: SubjectType; setSubjectType: (type: SubjectType) => void; subject: string; setSubject: (value: string) => void; query: string; setQuery: (value: string) => void }) {
  const allSubjects = useMemo(() => Array.from(new Set(schedule.lessons.map((lesson) => lesson.subject))).sort((a, b) => a.localeCompare(b, "es")), []);
  const allowed = (lesson: Lesson) => { if (subject !== "all" && lesson.subject !== subject) return false; if (subjectType === "tutoring" && lesson.primary !== schedule.tutors[lesson.group as keyof typeof schedule.tutors]) return false; if (["core", "lang", "spec"].includes(subjectType) && family(lesson.subject) !== subjectType) return false; return matches(query, lesson.subject, lesson.primary, ...lesson.shared, lesson.group, lesson.day); };
  return <><Toolbar query={query} setQuery={setQuery}><label>Tipo<select value={subjectType} onChange={(event) => setSubjectType(event.target.value as SubjectType)}><option value="all">Todas</option><option value="tutoring">Tutoría</option><option value="core">Troncales</option><option value="lang">Idiomas</option><option value="spec">Especialidades</option></select></label><label>Asignatura<select value={subject} onChange={(event) => setSubject(event.target.value)}><option value="all">Todas las asignaturas</option>{allSubjects.map((name) => <option key={name}>{name}</option>)}</select></label></Toolbar><section className="panel subject-overview"><PanelTitle eyebrow="Distribución por asignatura" title={subject === "all" ? "Todas las asignaturas" : subject}/><div className="matrix-wrap"><div className="subject-matrix"><div className="matrix-heading">Grupo</div>{DAYS.map((day) => <div className="matrix-heading" key={day}>{day}</div>)}{GROUPS.map((group) => <div className="matrix-row" key={group}><div className="matrix-group">{group}</div>{DAYS.map((day) => { const dayLessons = lessonsFor(group, day).filter(allowed); return <div className="subject-cell" key={day}>{dayLessons.length ? dayLessons.map((lesson) => <LessonCard key={lesson.time} lesson={lesson} query="" compact/>) : <span className="empty">—</span>}</div>; })}</div>)}</div></div></section></>;
}

function TeacherView({ teacher, setTeacher, teacherType, setTeacherType, query, setQuery }: { teacher: string; setTeacher: (name: string) => void; teacherType: TeacherType; setTeacherType: (type: TeacherType) => void; query: string; setQuery: (value: string) => void }) {
  const roleName: Record<TeacherType, string> = { all: "", tutors: "Tutor/a", specialists: "Especialista", shared: "Docencia compartida", support: "Apoyo disponible" };
  const filteredTeachers = TEACHERS.filter((name) => !roleName[teacherType] || schedule.teacherRoles[name]?.includes(roleName[teacherType]));
  useEffect(() => { if (!filteredTeachers.includes(teacher)) setTeacher(filteredTeachers[0] ?? TEACHERS[0]); }, [teacherType]);
  const load = schedule.teacherLoads[teacher];
  const extra = schedule.complementaryEvents.filter((event) => event.teacher === teacher && event.schedule.includes("14:00–15:00"));
  return <><Toolbar query={query} setQuery={setQuery}><label>Docente<select value={teacher} onChange={(event) => setTeacher(event.target.value)}>{filteredTeachers.map((name) => <option key={name}>{name}</option>)}</select></label><label>Tipo de docente<select value={teacherType} onChange={(event) => setTeacherType(event.target.value as TeacherType)}><option value="all">Todos</option><option value="tutors">Tutores</option><option value="specialists">Especialistas</option><option value="shared">Docencia compartida</option><option value="support">Apoyo disponible</option></select></label><button className="primary" onClick={() => window.print()}>Imprimir horario</button></Toolbar><section className="panel teacher-summary"><div><p className="eyebrow">Horario individual</p><h2>{teacher}</h2><p>{schedule.teacherRoles[teacher]?.join(" · ") || "Funciones no lectivas"}</p></div>{load && <div className="summary-stats">{summaryStat("Total semanal", load.total, true)}{summaryStat("Docencia", load.direct)}{summaryStat("Docencia compartida", load.shared)}{summaryStat("Recreo", load.recess)}{summaryStat("Complementarias", load.family + load.coordination)}{summaryStat("Reducción tutorial", load.tutorial)}{summaryStat("Apoyo", load.support)}</div>}</section>{extra.map((event) => <div className="notice" key={event.schedule}><b>Excepción autorizada:</b> {event.concept} · {event.schedule}. No constituye incidencia.</div>)}<section className="panel teacher-days">{DAYS.map((day) => <TeacherDay key={day} teacher={teacher} day={day} query={query}/>)}</section></>;
}
function summaryStat(label: string, value: number, primary = false) { return <div className={`summary-stat ${primary ? "total" : ""}`}><strong>{formatMinutes(value)}</strong><span>{label}</span></div>; }
function TeacherDay({ teacher, day, query }: { teacher: string; day: string; query: string }) { const rows = schedule.teacherMatrix.filter((row) => row.day === day); return <div className="teacher-day"><h3>{day}</h3>{rows.map((row) => { const state = row.teachers[teacher as keyof typeof row.teachers] || ""; const muted = !matches(query, state, teacher); return <article className={`teacher-entry ${statusClass(state)} ${muted ? "muted" : ""}`} key={row.time}><span>{row.time}</span><strong>{state || "—"}</strong></article>; })}</div>; }
function statusClass(status: string) { if (status.startsWith("DC ")) return "state-shared"; if (status.startsWith("Apoyo")) return "state-support"; if (status === "RECREO") return "state-recess"; if (status.includes("Atención a familias") || status.includes("Coordinación") || status.includes("Reducción")) return "state-complementary"; if (status === "NO DISPONIBLE") return "state-unavailable"; return "state-direct"; }

function LoadsView() { return <section className="panel loads"><PanelTitle eyebrow="Cómputo docente V2" title="Cargas semanales" aside={<span className="validation">Fuente: Excel V2</span>}/><div className="load-table"><div className="load-row head"><span>Docente</span><span>Docencia</span><span>Docencia compartida</span><span>Recreo</span><span>At. familias</span><span>Coordinación</span><span>Reducción tutorial</span><span>Horas computadas</span><span>Apoyo</span><span>Total semanal</span></div>{TEACHERS.map((teacher) => { const load = schedule.teacherLoads[teacher]; return <div className="load-row" key={teacher}><strong>{teacher}</strong><span>{formatMinutes(load.direct)}</span><span>{formatMinutes(load.shared)}</span><span>{formatMinutes(load.recess)}</span><span>{formatMinutes(load.family)}</span><span>{formatMinutes(load.coordination)}</span><span>{formatMinutes(load.tutorial)}</span><strong>{formatMinutes(load.computed)}</strong><span>{formatMinutes(load.support)}</span><strong className="load-total">{formatMinutes(load.total)}</strong></div>; })}</div><p className="table-note">“Apoyo” identifica únicamente los huecos residuales disponibles. La segunda persona dentro del aula se computa como docencia compartida.</p></section>; }

function SubstitutionsView() {
  const [view, setView] = useState<SubstitutionView>("resolver"); const [day, setDay] = useState("Lunes"); const [absent, setAbsent] = useState<string[]>([]); const [slot, setSlot] = useState(schedule.slots.Lunes[0]); const [query, setQuery] = useState(""); const [assignments, setAssignments] = useState<Record<string, string>>({});
  useEffect(() => { const daySlots = schedule.slots[day as keyof typeof schedule.slots]; if (!daySlots.includes(slot)) setSlot(daySlots[0]); setAssignments({}); }, [day]);
  const scenarios = substitutions.scenarios.filter((scenario) => scenario["Día"] === day && absent.includes(scenario["Docente ausente"]) && matches(query, scenario["Docente ausente"], scenario["Actividad"], scenario["Grupo"], scenario["Franja"]));
  const competition = candidateCompetition(scenarios, absent); const toggleAbsent = (teacher: string) => setAbsent((current) => current.includes(teacher) ? current.filter((name) => name !== teacher) : [...current, teacher]);
  return <><div className="sub-tabs"><button className={view === "resolver" ? "active" : ""} onClick={() => setView("resolver")}>Resolver faltas</button><button className={view === "availability" ? "active" : ""} onClick={() => setView("availability")}>Disponibilidad por franja</button></div>{view === "resolver" ? <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar falta, grupo o asignatura…"><label>Día<select value={day} onChange={(event) => setDay(event.target.value)}>{DAYS.map((name) => <option key={name}>{name}</option>)}</select></label></Toolbar><section className="sub-layout"><aside className="panel absence-picker"><p className="eyebrow">Docentes ausentes</p><h2>Selecciona uno o varios</h2><div>{TEACHERS.map((teacher) => <label key={teacher}><input type="checkbox" checked={absent.includes(teacher)} onChange={() => toggleAbsent(teacher)}/><span>{teacher}</span></label>)}</div></aside><section className="sub-results">{absent.length === 0 && <div className="panel empty-state"><b>Selecciona el día y el personal ausente.</b><span>Se mostrarán todas sus sesiones y candidatos P1 → P6.</span></div>}{absent.length > 0 && scenarios.length === 0 && <div className="panel empty-state"><b>No hay sesiones lectivas coincidentes.</b><span>Comprueba los filtros o selecciona otro día.</span></div>}{Object.keys(competition).length > 0 && <div className="warning"><b>Competencia detectada:</b> {Object.entries(competition).map(([key, names]) => `${key}: ${names.join(", ")}`).join(" · ")}. El sistema impide asignar una persona dos veces en la misma franja.</div>}{scenarios.map((scenario) => <ScenarioCard key={scenarioKey(scenario)} scenario={scenario} absent={absent} assignments={assignments} setAssignments={setAssignments}/>)}</section></section></> : <AvailabilityView day={day} setDay={setDay} slot={slot} setSlot={setSlot} query={query} setQuery={setQuery}/>}</>;
}
function scenarioKey(scenario: Scenario) { return `${scenario["Día"]}|${scenario["Franja"]}|${scenario["Docente ausente"]}`; }
function scenarioCandidates(scenario: Scenario, absent: string[]) { return PRIORITIES.map(([field, label], index) => ({ priority: index + 1, label, teachers: (scenario[field] || "").split(",").map((name) => name.trim()).filter((name) => name && name !== "—" && !absent.includes(name)) })); }
function candidateCompetition(scenarios: Scenario[], absent: string[]) { const occurrences = new Map<string, string[]>(); for (const scenario of scenarios) { const optional = scenario["Rol ausente"].toLocaleLowerCase("es").includes("compartida") && scenario["Cobertura obligatoria"] !== "Sí"; const groups = scenarioCandidates(scenario, absent).filter((group) => !optional || group.priority > 1); const first = groups.find((group) => group.teachers.length); if (!first) continue; for (const teacher of first.teachers) { const key = `${scenario["Franja"]}|${teacher}`; occurrences.set(key, [...(occurrences.get(key) || []), scenario["Grupo"]]); } } return Object.fromEntries([...occurrences].filter(([, groups]) => groups.length > 1).map(([key, groups]) => [key.replace("|", " · "), groups])); }
function ScenarioCard({ scenario, absent, assignments, setAssignments }: { scenario: Scenario; absent: string[]; assignments: Record<string, string>; setAssignments: (value: Record<string, string>) => void }) {
  const key = scenarioKey(scenario); const allGroups = scenarioCandidates(scenario, absent); const optional = scenario["Rol ausente"].toLocaleLowerCase("es").includes("compartida") && scenario["Cobertura obligatoria"] !== "Sí"; const groups = allGroups.filter((group) => !optional || group.priority > 1); const principalPresent = allGroups[0]?.teachers.join(", "); const reserved = new Set(Object.entries(assignments).filter(([otherKey, teacher]) => otherKey !== key && otherKey.startsWith(`${scenario["Día"]}|${scenario["Franja"]}|`) && teacher).map(([, teacher]) => teacher));
  return <article className="panel scenario-card"><div className="scenario-head"><div><span>{scenario["Franja"]} · {scenario["Grupo"]}</span><h3>{scenario["Actividad"]}</h3></div><span className={`role-badge ${optional ? "optional" : ""}`}>{scenario["Rol ausente"]}</span></div><p><b>Ausente:</b> {scenario["Docente ausente"]}</p>{optional && <div className="dc-note">Grupo atendido por docente principal — reposición de docencia compartida opcional{principalPresent ? ` · Presente: ${principalPresent}` : ""}</div>}<div className="priority-list">{groups.map((group) => <div className="priority-row" key={group.priority}><b>{group.label}</b><span>{group.teachers.length ? group.teachers.map((teacher) => <i key={teacher}>{teacher}{reserved.has(teacher) ? " · ya asignado" : ""}</i>) : <em>Sin candidatos</em>}</span></div>)}<div className="priority-row"><b>P6 · Equipo directivo</b><span><i>Equipo directivo — consultar disponibilidad</i></span></div></div><label className="assignment">Asignación manual<select value={assignments[key] || ""} onChange={(event) => setAssignments({ ...assignments, [key]: event.target.value })}><option value="">Sin asignar</option>{groups.map((group) => <optgroup key={group.priority} label={group.label}>{group.teachers.map((teacher) => <option key={teacher} value={teacher} disabled={reserved.has(teacher)}>{teacher}{reserved.has(teacher) ? " — ocupado en esta franja" : ""}</option>)}</optgroup>)}</select></label>{scenario["Observaciones"] && <small className="scenario-note">{scenario["Observaciones"]}</small>}</article>;
}
function AvailabilityView({ day, setDay, slot, setSlot, query, setQuery }: { day: string; setDay: (day: string) => void; slot: string; setSlot: (slot: string) => void; query: string; setQuery: (value: string) => void }) {
  const daySlots = schedule.slots[day as keyof typeof schedule.slots]; const current = substitutions.slots.find((item) => item.day === day && item.slot === slot); const categories = [["p2", "P2 · Apoyo"], ["p3", "P3 · Docencia compartida disponible para movilización"], ["p4", "P4 · Atención a familias"], ["p5", "P5 · Coordinación / reducción tutorial"]];
  if (isRecess(day, slot)) return <><Toolbar query={query} setQuery={setQuery}><label>Día<select value={day} onChange={(event) => setDay(event.target.value)}>{DAYS.map((name) => <option key={name}>{name}</option>)}</select></label><label>Franja<select value={slot} onChange={(event) => setSlot(event.target.value)}>{daySlots.map((time) => <option key={time}>{time}</option>)}</select></label></Toolbar><div className="panel recess-warning"><b>Vigilancia de recreo pendiente de cuadrante específico</b><span>No se infiere disponibilidad durante el recreo.</span></div></>;
  return <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar docente o actividad…"><label>Día<select value={day} onChange={(event) => setDay(event.target.value)}>{DAYS.map((name) => <option key={name}>{name}</option>)}</select></label><label>Franja<select value={slot} onChange={(event) => setSlot(event.target.value)}>{daySlots.map((time) => <option key={time}>{time}</option>)}</select></label></Toolbar><section className="availability-grid">{categories.map(([kind, title]) => { const people = Object.entries(current?.teachers || {}).filter(([teacher, state]) => state.kind === kind && matches(query, teacher, state.status)); return <article className="panel availability-card" key={kind}><h3>{title}</h3>{people.length ? people.map(([teacher, state]) => <div key={teacher}><b>{teacher}</b><span>{state.status}</span></div>) : <p>Sin disponibilidad en esta prioridad.</p>}</article>; })}<article className="panel availability-card unavailable-list"><h3>No disponibles · docencia directa</h3>{Object.entries(current?.teachers || {}).filter(([teacher, state]) => (state.kind === "docencia" || state.kind === "no_disponible") && matches(query, teacher, state.status)).map(([teacher, state]) => <div key={teacher}><b>{teacher}</b><span>{state.status}</span></div>)}</article><article className="panel availability-card directivo-card"><h3>P6 · Equipo directivo</h3><p>Equipo directivo — consultar disponibilidad</p></article></section></>;
}
